### ISSUE TITLE
Zombienet Warp Sync: template-simple-node does not produce blocks

### ISSUE THREAD

**Issue by Chralt98** [moondance-labs/tanssi#286]
Hey tanssi team,

I successfully generated the necessary binary files (tanssi, polkadot, container-chain-template-simple-node) for the execution of the following commands from the README.md:

```
# Generates the latest specs for orchestrator and container-chains
npm run build-spec

# Spawns Tanssi and container-chains with zombienet
/path/to/zombienet spawn -p native ./configs/zombieTanssiWarpSync.json
```

Now I go to the polkadot js interface and see all collators and polkadot validators producing blocks, except the `container-chain-template-simple-node` does not. Do you experience the same issue?

**Comment by Chralt98** [comment]
For the tanssi collators I needed to wait until they produce blocks. For the template simple node I assume I need to wait even longer until it is registered as a parachain on the rococo local testnet, right? But how long is it configured?

**Comment by Chralt98** [comment]
I try to use the polkadot version you use in your repository and try it again then.

**Comment by girazoki** [comment]
Simple template and frontier template runtimes take at least one session in tanssi to start producing blocks. If you compile with `fast-runtime` one session should take 5 blocks (around one minute)

**Comment by tmpolaczyk** [comment]
The readme already includes instructions to compile with fast-runtime: `cargo build --features=fast-runtime --release`

Closing
