### ISSUE TITLE
How to switch between multiple zombienet instance logs using moonwall?

### ISSUE THREAD

**Issue by Chralt98** [moondance-labs/tanssi#304]
I currently use the moonwall TUI interface and there is the option to see the logs for the current running node. 

How can I switch to another node, assuming I have a configuration with multiple spawned networks?

**Comment by tmpolaczyk** [comment]
Personally I just open a new terminal and check the logs in /tmp, as described in the test/readme.md: https://github.com/moondance-labs/tanssi/blob/master/test/README.md

**Comment by tmpolaczyk** [comment]
Fixed in the next moonwall version
