### ISSUE TITLE
Ran out of free WASM instances

### ISSUE THREAD

**Issue by stakeworks** [moondance-labs/tanssi#485]
The last 2 days the Orchestrator, Container and Relaychain increasingly ran out of free WASM instances.

![image](https://github.com/moondance-labs/tanssi/assets/19406838/151a5ff5-cf58-4500-88c7-a5cdaedb51e3)

It went on after a restart of the Tanssi-node. 
Increasing the setting --max-runtime-instances to 32 seems to solve the problem.

Binary version: tanssi-node 0.5.2-07be0f3e963
Ubuntu: Ubuntu 22.04.4 LTS

ExecStart=/usr/local/bin/tanssi/tanssi-node \
        --collator \
        --chain dancebox \
        --database paritydb \
        --base-path=/basepath \
        --name='StakeWorks | Tanssi' \
        --trie-cache-size 268435456 \
        --no-private-ip \
        --max-parallel-downloads 7 \
        --max-runtime-instances 32 \
        --no-hardware-benchmarks \
        --out-peers 15 \
        --in-peers 35 \
        --listen-addr /ip4/xx.xx.xx.xx/tcp/30333/ws \
        --rpc-port 9944 \
        --prometheus-port 1234 \
        --prometheus-external \
        --telemetry-url='wss://telemetry.polkadot.io/submit/ 0' \
        --state-pruning=2000 \
        --blocks-pruning=2000 \
        -- \
        --base-path=/basepath \
        --name=tanssi-appchain \
        --trie-cache-size 268435456 \
        --no-private-ip \
        --max-parallel-downloads 7 \
        --max-runtime-instances 32 \
        --listen-addr /ip4/xx.xx.xx.xx/tcp/30334/ws \
        --rpc-port=9945 \
        --telemetry-url='wss://telemetry.polkadot.io/submit/ 0' \
        -- \
        --name='StakeWorks | Tanssi' \
        --chain westend_moonbase_relay_testnet \
        --database paritydb \
        --max-runtime-instances 32 \
        --no-private-ip \
        --no-hardware-benchmarks \
        --listen-addr /ip4/xx.xx.xx.xx/tcp/30335/ws \
        --rpc-port=9946 \
        --telemetry-url='wss://telemetry.polkadot.io/submit/ 0' \
        --sync fast \
        --base-path=/home/tanssi/.tanssi-collator \
        --state-pruning=2000 \
        --blocks-pruning=2000 \

Update:
20240308: No "Ran out of free WASM instances" since yesterday after increasing --max-runtime-instances to 32

**Comment by girazoki** [comment]
We are looking into this, thank you @stakeworks ! In the meantime can you tell us whether you are doing requests to the rpc (specially, to the relay one?) Also is this something you see always? or was it a one-time log?

**Comment by stakeworks** [comment]
_In the meantime can you tell us whether you are doing requests to the rpc (specially, to the relay one?)_ 
Not doing RPC requests and RPC ports are closed for outside requests. 

_Also is this something you see always? or was it a one-time log?_
It started on April 2nd at 21:11 hour. I've added the logs from April 4th until now.

[tanssi.zip](https://github.com/moondance-labs/tanssi/files/14904231/tanssi.zip)

**Comment by girazoki** [comment]
We ocasionally observe the `"Ran out of free WASM instances"` but in very rare ocassions, your node is showing it too frequently with respect to what we can observe. We are working to relax (a bit) the number of instances at the same time needed but we dont understand why your specific node shows that many. In any case this is not a critical error and you can run with more instance if needed (as you did with 32)

Thanks for reporting!

**Comment by girazoki** [comment]
Please let us know if you still observe this error after running with more instances

**Comment by tmpolaczyk** [comment]
If you are curious, you can set `export RUST_LOG=info,executor=trace` to see what is being executed when the node runs out of free instances, but I agree that this is not critical so just setting a higher limit will be enough.

**Comment by stakeworks** [comment]
Is there a max WASM instances per chain or in total? 
Do these settings affect the number of WASM instances?
--trie-cache-size 268435456
--max-parallel-downloads 7
--out-peers 15
--in-peers 35

**Comment by tmpolaczyk** [comment]
> Is there a max WASM instances per chain or in total?

It's per chain (actually per runtime version), and the limit of the relay chain should be higher because all chains use the relay chain.

> Could be because the node is running on a heavy server? It's a 16 core

It's possible that with a higher core count your node can perform more tasks in parallel, so yes.

Looking at the code it is not clear to me why that instance cache is needed, because creating a new instance seems to be free. And increasing the number of instances is also free. So I recommend to just set it to 32 and ignore future warnings, unless they cause some other issues such as problems to keep in sync or they affect block production.
