### ISSUE TITLE
Tanssi collator assignation detection pallet

### ISSUE THREAD

**Issue by girazoki** [moondance-labs/tanssi#52]
We need to create a pallet that is able to insert and store the collators assigned to a given ContainerChain. This pallet would be incorporated by containerChains to allow for block production author verification.

The way to do it should be initially similar to author-noting. We should read the header of the Tanssi parachain from the relay (the Tanssi paraId should be stored in the pallet as a storage item that can be initialized in Genesis) and provide a storage root to the pallet, proving the header is actually legit.

For now this should be sufficient to start

**Comment by tmpolaczyk** [comment]
Done
