### ISSUE TITLE
arm Tanssi v app

### ISSUE THREAD

**Issue by ysn100ysn** [moondance-labs/tanssi#542]
When will the application be made for ARM architecture?

**Comment by tmpolaczyk** [comment]
Hi, we have no plans to include an ARM release, but you can compile it for ARM yourself, it should work. Remember that running a collator node on ARM is not recommended because of the minimum hardware requirements, but you should be able to run a full node.

**Comment by girazoki** [comment]
Closing because it is not forecasted
