### ISSUE TITLE
Create containerChain template for testing purposes

### ISSUE THREAD

**Issue by girazoki** [moondance-labs/tanssi#58]
The idea is that we create something similar to https://github.com/paritytech/cumulus/tree/master/parachain-template

This should mimic a **ContainerChain** runtime. This is, it should not have any other consensus than the one offered by Tanssi, it should incorporate the pallets that allow Tanssi to work and it should work with the Tanssi collators

**Comment by tmpolaczyk** [comment]
Done :)
